FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем utils для логирования
COPY utils/ ./utils/

COPY bot/ ./bot/

# Создаём директорию для логов
RUN mkdir -p /app/logs

ENV PYTHONPATH=/app

CMD ["python", "-m", "bot.bot_v3"]