"""add base for global users

Revision ID: 1c9c78824fc8
Revises: 800a66f40c24
Create Date: 2026-05-04 12:14:02.290753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c9c78824fc8'
down_revision = '800a66f40c24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chat_history', sa.Column('global_user_id', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('global_user_id', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('sent_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('news', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('subscribers', sa.Column('platform', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'platform')
    op.drop_column('news', 'source')
    op.drop_column('news', 'sent_channels')
    op.drop_column('events', 'global_user_id')
    op.drop_column('chat_history', 'global_user_id')
    op.drop_table('users')
    op.drop_table('user_accounts')
    # ### end Alembic commands ###
