"""migrate to block users in ui

Revision ID: 2230067e5d57
Revises: 39d00624c75b
Create Date: 2026-05-06 09:19:20.201157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2230067e5d57'
down_revision = '39d00624c75b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'global_user_id')
    op.drop_column('search_results', 'score')
    op.alter_column('users', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('uq_users_phone'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_phone'), 'users', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('search_results', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('global_user_id', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
