"""add ui_users table

Revision ID: 595c413fc9cc
Revises: 1c9c78824fc8
Create Date: 2026-05-04 13:41:20.958629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595c413fc9cc'
down_revision = '1c9c78824fc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ui_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_unique_constraint('uq_users_phone', 'users', ['phone_number'])

    op.execute("""
        ALTER TABLE users 
        ALTER COLUMN id SET DEFAULT gen_random_uuid()::text
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("""
        ALTER TABLE users 
        ALTER COLUMN id DROP DEFAULT
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ui_users')
    op.drop_constraint('uq_users_phone', 'users', type_='unique')
    # ### end Alembic commands ###
