"""fix_missing_fields

Revision ID: 800a66f40c24
Revises: b2c3d4e5f6a7
Create Date: 2026-04-30 13:52:13.616113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800a66f40c24'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('ui_users')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ui_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ui_users_pkey')),
    sa.UniqueConstraint('username', name=op.f('ui_users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
